// Auth actions
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Employees actions
export const EMPLOYEES_FETCH_START = "EMPLOYEES_FETCH_START";
export const EMPLOYEES_FETCH_SUCCESS = "EMPLOYEES_FETCH_SUCCESS";
export const EMPLOYEES_FETCH_FAIL = "EMPLOYEES_FETCH_FAIL";
// Employee actions
export const EMPLOYEE_SELECT = "EMPLOYEE_SELECT";
export const EMPLOYEE_FETCH_START = "EMPLOYEE_FETCH_START";
export const EMPLOYEE_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";
export const EMPLOYEE_FETCH_FAIL = "EMPLOYEE_FETCH_FAIL";
export const EMPLOYEE_ADD_START = "EMPLOYEE_ADD_START";
export const EMPLOYEE_ADD_SUCCESS = "EMPLOYEE_ADD_SUCCESS";
export const EMPLOYEE_ADD_FAIL = "EMPLOYEE_ADD_FAIL";
export const EMPLOYEE_EDIT_START = "EMPLOYEE_EDIT_START";
export const EMPLOYEE_EDIT_SUCCESS = "EMPLOYEE_EDIT_SUCCESS";
export const EMPLOYEE_EDIT_FAIL = "EMPLOYEE_EDIT_FAIL";
export const EMPLOYEE_CANCEL = "EMPLOYEE_CANCEL";
export const EMPLOYEE_DELETE_START = "EMPLOYEE_DELETE_START";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL";

// Customers
export const CUSTOMERS_FETCH_START = "CUSTOMERS_FETCH_START";
export const CUSTOMERS_FETCH_SUCCESS = "CUSTOMERS_FETCH_SUCCESS";
export const CUSTOMERS_FETCH_FAIL = "CUSTOMERS_FETCH_FAIL";
export const CUSTOMER_SELECTED = "CUSTOMER_SELECTED";
export const CUSTOMER_EDITED = "CUSTOMER_EDITED";

// Projects
export const PROJECTS_FETCH_START = "PROJECTS_FETCH_START";
export const PROJECTS_FETCH_SUCCESS = "PROJECTS_FETCH_SUCCESS";
export const PROJECTS_FETCH_FAIL = "PROJECTS_FETCH_FAIL";
export const PROJECT_SELECTED = "PROJECT_SELECTED";
export const PROJECT_EDITED = "PROJECT_EDITED";

// Project

export const PROJECT_SELECT = "PROJECT_SELECT";
export const PROJECT_FETCH_START = "PROJECT_FETCH_START";
export const PROJECT_FETCH_SUCCESS = "PROJECT_FETCH_SUCCESS";
export const PROJECT_FETCH_FAIL = "PROJECT_FETCH_FAIL";
export const PROJECT_ADD_START = "PROJECT_ADD_START";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_ADD_FAIL = "PROJECT_ADD_FAIL";
export const PROJECT_EDIT_START = "PROJECT_EDIT_START";
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS";
export const PROJECT_EDIT_FAIL = "PROJECT_EDIT_FAIL";
export const PROJECT_CANCEL = "PROJECT_CANCEL";
export const PROJECT_DELETE_START = "PROJECT_DELETE_START";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";

// Calendar
export const LOAD_CALENDAR_MONTH = "LOAD_CALENDAR_MONTH";
export const LOAD_CALENDAR_MONTH_SUCCESS = "LOAD_CALENDAR_MONTH_SUCCESS";
export const LOAD_CALENDAR_MONTH_FAIL = "LOAD_CALENDAR_MONTH_FAIL";

// Task
export const TASK_EDITED_SUCCESS = "TASK_EDITED_SUCCESS";
export const TASK_EDITED_START = "TASK_EDITED_START";
export const TASK_EDITED_FAIL = "TASK_EDITED_FAIL";
export const TASK_ADD_START = "TASK_EDITED_START";
export const TASK_ADD_SUCCESS = "TASK_EDITED_SUCCESS";
export const TASK_ADD_FAIL = "TASK_EDITED_FAIL";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_START = "TASK_DELETE_START";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";
export const ADD_DAY_WITH_TASK_SUCCESS = "ADD_DAY_WITH_TASK_SUCCESS";
export const ADD_DAY_WITH_TASK_START = "ADD_DAY_WITH_TASK_START";
export const ADD_DAY_WITH_TASK_FAIL = "ADD_DAY_WITH_TASK_FAIl";
export const ADD_DAY_SUCCESS = "ADD_DAY_SUCCESS";
export const ADD_DAY_FAIL = "ADD_DAY_FAIL";
export const ADD_DAY_START = "ADD_DAY_START";
export const RELOAD_CALENDAR = "RELOAD_CALENDAR";
export const DAY_EDITED_SUCCESS = "TASK_EDITED_SUCCESS";
export const DAY_EDITED_FAIL = "TASK_EDITED_FAIL";

// Team Tracking
export const TEAMTRACKING_FETCH_START = "TEAMTRACKING_FETCH_START";
export const TEAMTRACKING_FETCH_SUCCESS = "TEAMTRACKING_FETCH_SUCCESS";
export const TEAMTRACKING_FETCH_FAIL = "TEAMTRACKING_FETCH_FAIL";

// Dropdown team
export const DROPDOWNTEAM_FETCH_START = "DROPDOWNTEAM_FETCH_START";
export const DROPDOWNTEAM_FETCH_SUCCESS = "DROPDOWNTEAM_FETCH_SUCCESS";
export const DROPDOWNTEAM_FETCH_FAIL = "DROPDOWNTEAM_FETCH_FAIL";
export const DROPDOWNTEAM_SELECT = "DROPDOWNTEAM_SELECT";
// Dropdown month
export const DROPDOWNMONTH_SELECT = "DROPDOWNMONTH_SELECT";
// Dropdown year
export const DROPDOWNYEAR_SELECT = "DROPDOWNYEAR_SELECT";

export const PERSONAL_REPORT_START = "PERSONAL_REPORT_START";
export const PERSONAL_REPORT_SUCCESS = "PERSONAL_REPORT_SUCCESS";
export const PERSONAL_REPORT_FAIL = "PERSONAL_REPORT_FAIL";

// Company Dashboard
export const COMPANY_DASHBOARD_START = "COMPANY_DASHBOARD_START";
export const COMPANY_DASHBOARD_SUCCESS = "COMPANY_DASHBOARD_SUCCESS";
// Annual report
export const FETCH_ANNUAL_REPORT = "FETCH_ANNUAL_REPORT";
export const FETCH_ANNUAL_REPORT_SUCCESS = "FETCH_ANNUAL_REPORT_SUCCESS";
export const FETCH_ANNUAL_REPORT_FAILURE = "FETCH_ANNUAL_REPORT_FAILURE";
export const START_ANNUAL_REPORT_LOADER = "START_ANNUAL_REPORT_LOADER";

// Monthly report
export const FETCH_MONTHLY_REPORT = "FETCH_MONTHLY_REPORT";
export const FETCH_MONTHLY_REPORT_SUCCESS = "FETCH_MONTHLY_REPORT_SUCCESS";
export const FETCH_MONTHLY_REPORT_FAILURE = "FETCH_MONTHLY_REPORT_FAILURE";
